"""integracion de presentacion_venta

Revision ID: 027f1187d1f8
Revises: 60babd594ba8
Create Date: 2026-04-04 16:46:40.139520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '027f1187d1f8'
down_revision = '60babd594ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentacion_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('idProductoBase', sa.Integer(), nullable=False),
    sa.Column('equivalencia', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idProductoBase'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fechaEliminacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('factura',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('idProveedor',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('idUsuario',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'usuario', ['idUsuario'], ['id'])

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.alter_column('stockActual',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('stockMinimo',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_index(batch_op.f('nombre'))
        batch_op.drop_constraint(batch_op.f('materia_prima_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('idProveedor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProveedor', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('materia_prima_ibfk_2'), 'proveedor', ['idProveedor'], ['id'])
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)
        batch_op.alter_column('stockMinimo',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('stockActual',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('idUsuario',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('idProveedor',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('factura',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('fechaEliminacion')
        batch_op.drop_column('estatus')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('presentacion_venta')
    # ### end Alembic commands ###
