"""agrega costoProduccion a receta

Revision ID: 233ce8ef5ff4
Revises: 6d3a624950e3
Create Date: 2026-04-15 02:00:38.701313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '233ce8ef5ff4'
down_revision = '6d3a624950e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversiones', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('detalleventa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idPresentacion', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'presentacion_venta', ['idPresentacion'], ['id'])

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.alter_column('stockActual',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('stockMinimo',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idCliente', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'cliente_externo', ['idCliente'], ['id'])
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombreCliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombreCliente', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idCliente')

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.alter_column('stockMinimo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('stockActual',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('detalleventa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idPresentacion')

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('conversiones', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
