"""empty message

Revision ID: 60babd594ba8
Revises: 0dc86657962c
Create Date: 2026-04-02 18:47:59.566170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60babd594ba8'
down_revision = '0dc86657962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fechaEliminacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('cantidad',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('fechaEliminacion')
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
