"""add pedido y detalle_pedido

Revision ID: 69b432c4cc84
Revises: bd7ce6f3cd16
Create Date: 2026-04-09 09:58:57.314259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b432c4cc84'
down_revision = 'bd7ce6f3cd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('nombreCliente', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('fechaPedido', sa.DateTime(), nullable=False),
    sa.Column('fechaRecogida', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('detalle_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPedido', sa.Integer(), nullable=False),
    sa.Column('idPresentacion', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioUnitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idPedido'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['idPresentacion'], ['presentacion_venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversiones', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('conversiones', schema=None) as batch_op:
        batch_op.alter_column('factor',
               existing_type=mysql.FLOAT(),
               nullable=True)

    op.drop_table('detalle_pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
