"""empty message

Revision ID: a0da59438d8a
Revises: 233ce8ef5ff4
Create Date: 2026-04-15 10:21:25.267599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0da59438d8a'
down_revision = '233ce8ef5ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_externo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pedido_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cliente_externo', ['idCliente'], ['id'])

    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costoProduccion', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.drop_column('costoProduccion')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_ibfk_1'), 'usuario', ['idCliente'], ['id'])

    op.drop_table('cliente_externo')
    # ### end Alembic commands ###
