"""add idReceta y lotes

Revision ID: a36b0e83266c
Revises: 233ce8ef5ff4
Create Date: 2026-04-15 12:16:13.985948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a36b0e83266c'
down_revision = '233ce8ef5ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idReceta', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lotes', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'receta', ['idReceta'], ['id'])
        batch_op.drop_column('cantidad_solicitada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_solicitada', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lotes')
        batch_op.drop_column('idReceta')

    # ### end Alembic commands ###
