"""merma cantidad a decimal

Revision ID: bd7ce6f3cd16
Revises: c6d8764d9126
Create Date: 2026-04-05 13:18:04.607943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd7ce6f3cd16'
down_revision = 'c6d8764d9126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merma', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
