"""empty message

Revision ID: eaf7dc325616
Revises: 60babd594ba8
Create Date: 2026-04-02 19:48:33.789854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaf7dc325616'
down_revision = '60babd594ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('conversiones')
    op.drop_table('solicitudproduccion')
    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.Boolean(), nullable=True))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUsuario', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('venta_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['idUsuario'], ['id'])
        batch_op.drop_column('idTurno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idTurno', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('venta_ibfk_1'), 'turno', ['idTurno'], ['id'])
        batch_op.drop_column('idUsuario')

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    op.create_table('solicitudproduccion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('estatus', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('idProducto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.id'], name=op.f('solicitudproduccion_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conversiones',
    sa.Column('unidadBase', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('presentacion', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('factor', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('unidadBase', 'presentacion'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
